Migrating Patient contacts not yet registered as Patients
palladiumkenya/openmrs-module-kenyaemrhivtesting pull request #307
Opened 2024-09-17 06:34 UTC by njorocs

**@ojwanganto , as the code is,  it is throwing this error.**

`ERROR - Listener.contextInitialized(266) |2024-09-17T09:25:44,187| Failed to obtain JDBC connection
org.openmrs.module.ModuleException: Unable to start OpenMRS. Error thrown was: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'coreContext': Unsatisfied dependency expressed through method 'setManagers' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'choreManager': Unsatisfied dependency expressed through field 'allChores'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'hivtestingservices.chore.MigrateUnregisteredPatientContacts': Unsatisfied dependency expressed through field 'htsService'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.openmrs.module.hivtestingservices.api.HTSService' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.openmrs.web.WebDaemon.startOpenmrs(WebDaemon.java:69) ~[openmrs-web-2.6.5-SNAPSHOT.jar:?]
	at org.openmrs.web.Listener.contextInitialized(Listener.java:258) ~[openmrs-web-2.6.5-SNAPSHOT.jar:?]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4768) ~[tomcat9-catalina-9.0.58.jar:9.0.58]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5230) ~[tomcat9-catalina-9.0.58.jar:9.0.58]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat9-catalina-9.0.58.jar:9.0.58]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:726) ~[tomcat9-catalina-9.0.58.jar:9.0.58]
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:698) ~[tomcat9-catalina-9.0.58.jar:9.0.58]
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:696) ~[tomcat9-catalina-9.0.58.jar:9.0.58]
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1024) ~[tomcat9-catalina-9.0.58.jar:9.0.58]
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1911) ~[tomcat9-catalina-9.0.58.jar:9.0.58]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_422]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_422]
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) ~[tomcat9-util-9.0.58.jar:9.0.58]
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112) ~[?:1.8.0_422]
	at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:825) ~[tomcat9-catalina-9.0.58.jar:9.0.58]
	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:475) ~[tomcat9-catalina-9.0.58.jar:9.0.58]
	at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1618) ~[tomcat9-catalina-9.0.58.jar:9.0.58]
	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:319) ~[tomcat9-catalina-9.0.58.jar:9.0.58]
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123) ~[tomcat9-catalina-9.0.58.jar:9.0.58]
	at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423) ~[tomcat9-catalina-9.0.58.jar:9.0.58]
	at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366) ~[tomcat9-catalina-9.0.58.jar:9.0.58]
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:946) ~[tomcat9-catalina-9.0.58.jar:9.0.58]
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:835) ~[tomcat9-catalina-9.0.58.jar:9.0.58]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat9-catalina-9.0.58.jar:9.0.58]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1396) ~[tomcat9-catalina-9.0.58.jar:9.0.58]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1386) ~[tomcat9-catalina-9.0.58.jar:9.0.58]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_422]
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) ~[tomcat9-util-9.0.58.jar:9.0.58]
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134) ~[?:1.8.0_422]
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:919) ~[tomcat9-catalina-9.0.58.jar:9.0.58]
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:263) ~[tomcat9-catalina-9.0.58.jar:9.0.58]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat9-catalina-9.0.58.jar:9.0.58]
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:432) ~[tomcat9-catalina-9.0.58.jar:9.0.58]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat9-catalina-9.0.58.jar:9.0.58]
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:927) ~[tomcat9-catalina-9.0.58.jar:9.0.58]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat9-catalina-9.0.58.jar:9.0.58]
	at org.apache.catalina.startup.Catalina.start(Catalina.java:772) ~[tomcat9-catalina-9.0.58.jar:9.0.58]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_422]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_422]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_422]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_422]
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:345) ~[bootstrap.jar:9.0.58]
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:480) ~[bootstrap.jar:9.0.58]
Caused by: javax.servlet.ServletException: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'coreContext': Unsatisfied dependency expressed through method 'setManagers' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'choreManager': Unsatisfied dependency expressed through field 'allChores'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'hivtestingservices.chore.MigrateUnregisteredPatientContacts': Unsatisfied dependency expressed through field 'htsService'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.openmrs.module.hivtestingservices.api.HTSService' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.openmrs.web.Listener.startOpenmrs(Listener.java:377) ~[openmrs-web-2.6.5-SNAPSHOT.jar:?]
	at org.openmrs.web.WebDaemon$1.run(WebDaemon.java:42) ~[openmrs-web-2.6.5-SNAPSHOT.jar:?]
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'coreContext': Unsatisfied dependency expressed through method 'setManagers' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'choreManager': Unsatisfied dependency expressed through field 'allChores'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'hivtestingservices.chore.MigrateUnregisteredPatientContacts': Unsatisfied dependency expressed through field 'htsService'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.openmrs.module.hivtestingservices.api.HTSService' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.spri [...]

2024-09-17 09:19 UTC, ojwanganto commented on api/src/main/java/org/openmrs/module/hivtestingservices/chore/MigrateUnregisteredPatientContacts.java
> +import org.openmrs.*;
avoid star imports. Please configure your editor to have this disabled.

2024-09-17 09:27 UTC, ojwanganto commented on api/src/main/java/org/openmrs/module/hivtestingservices/chore/MigrateUnregisteredPatientContacts.java
> +import java.util.*;
optimize this import.

2024-09-17 09:30 UTC, ojwanganto commented on api/src/main/java/org/openmrs/module/hivtestingservices/chore/MigrateUnregisteredPatientContacts.java
> +        patientContacts.removeIf(patientContact -> patientContact.getPatient() != null || patientContact.getVoided());
should we also add those contacts who have been traced among those who have not been registered? This can help us avoid pulling contacts who were just listed and nothing done. This needs a discussion though

2024-09-17 09:35 UTC, ojwanganto commented on api/src/main/java/org/openmrs/module/hivtestingservices/chore/MigrateUnregisteredPatientContacts.java
> +            processBatch(batch);
To improve processing speed, you can do something like:
`if ((counter%500)==0) {
                Context.flushSession();
                Context.clearSession();
                counter=0;
            }`
You can simply append those at the end of the processBatch method although you might want to do away of the method altogether. I don't think it is adding anything important. The idea for batching is to help speed up performance

2024-09-24 10:21 UTC, njorocs commented on api/src/main/java/org/openmrs/module/hivtestingservices/chore/MigrateUnregisteredPatientContacts.java
> +        patientContacts.removeIf(patientContact -> patientContact.getPatient() != null || patientContact.getVoided());
If we exclude them, then users will never find them for tracing purposes.

2024-10-03 16:13 UTC, njorocs commented
![Screenshot from 2024-10-03 18-12-44](https://github.com/user-attachments/assets/b0988849-4ba2-4251-a9b8-813eea202ec4)

2024-10-10 12:29 UTC, ojwanganto commented on api/src/main/java/org/openmrs/module/hivtestingservices/chore/MigrateUnregisteredPatientContacts.java
> +            address.setAddress2("Unknown");
Do we need to have address if everything is set to unknown?

2024-10-10 12:30 UTC, ojwanganto commented on api/src/main/java/org/openmrs/module/hivtestingservices/chore/MigrateUnregisteredPatientContacts.java
> +        HTSService htsService = Context.getService(HTSService.class);
We can have this outside of the method. Probably as a class variable

2024-10-10 12:30 UTC, ojwanganto commented on api/src/main/java/org/openmrs/module/hivtestingservices/chore/MigrateUnregisteredPatientContacts.java
> +            PersonService personService = Context.getService(PersonService.class);
Let's have this outside of the method

2024-10-10 12:33 UTC, ojwanganto commented on api/src/main/java/org/openmrs/module/hivtestingservices/chore/MigrateUnregisteredPatientContacts.java
> +        ConceptService conceptService = Context.getService(ConceptService.class);
Let's remove these outside of the method.

2024-10-10 19:54 UTC, ojwanganto commented on api/src/main/java/org/openmrs/module/hivtestingservices/chore/MigrateUnregisteredPatientContacts.java
> +        Map<String, Concept> conceptCache = new HashMap<>();
How is this cache used?

2024-10-10 19:55 UTC, ojwanganto commented on api/src/main/java/org/openmrs/module/hivtestingservices/chore/MigrateUnregisteredPatientContacts.java
> +                obs.setConcept(concept);
Is there a possibility that the obs concept and value coded might be set to the same concept?

2024-10-11 09:17 UTC, njorocs commented on api/src/main/java/org/openmrs/module/hivtestingservices/chore/MigrateUnregisteredPatientContacts.java
> +        HTSService htsService = Context.getService(HTSService.class);
The suggested approach is what makes startup take infinitely long. See the time since beginning of context refresh
![Startup with services as Class variables](https://github.com/user-attachments/assets/5dde4f45-71d7-4a65-8e94-154c9f3dbe5a)

2024-10-11 17:40 UTC, ojwanganto commented on api/src/main/java/org/openmrs/module/hivtestingservices/chore/MigrateUnregisteredPatientContacts.java
> +        HTSService htsService = Context.getService(HTSService.class);
Sawa

2024-10-12 13:12 UTC, njorocs commented on api/src/main/java/org/openmrs/module/hivtestingservices/chore/MigrateUnregisteredPatientContacts.java
> +            address.setAddress2("Unknown");
Not neccessary. Removed them

2024-10-12 13:20 UTC, njorocs commented on api/src/main/java/org/openmrs/module/hivtestingservices/chore/MigrateUnregisteredPatientContacts.java
> +        Map<String, Concept> conceptCache = new HashMap<>();
Since the concepts are used for every call to saveObservations, which happens for every patient contact, the idea is to make a single call to the DB, load the concepts in the cache and subsequently read from it. In the event we get a concept ID not in the cache/miss, we then use the concept service to get the concept. I note the cache was not populated (now done in the last commit) and have also made it a class variable.

2024-10-12 13:26 UTC, njorocs commented on api/src/main/java/org/openmrs/module/hivtestingservices/chore/MigrateUnregisteredPatientContacts.java
> +                obs.setConcept(concept);
I do not see that happening.

2024-10-15 05:20 UTC, ojwanganto commented on api/src/main/java/org/openmrs/module/hivtestingservices/chore/MigrateUnregisteredPatientContacts.java
> +                obs.setValueCoded(conceptCache.computeIfAbsent(UNKNOWN, conceptService::getConceptByUuid));
what are we setting as the value here? we don't need to create obs if we don't have any valid answers

2024-10-16 04:42 UTC, ojwanganto commented on api/src/main/java/org/openmrs/module/hivtestingservices/chore/MigrateUnregisteredPatientContacts.java
> +                        saveObservations(newPatient.getPatientId(), encounter.getEncounterId(), pc.getMaritalStatus());
You still want to check for NULLs

2024-10-16 04:43 UTC, ojwanganto commented on api/src/main/java/org/openmrs/module/hivtestingservices/chore/MigrateUnregisteredPatientContacts.java
> +        Obs obs = new Obs();
Should this obs be added to the registration encounter?

2024-10-16 04:44 UTC, ojwanganto commented on api/src/main/java/org/openmrs/module/hivtestingservices/chore/MigrateUnregisteredPatientContacts.java
> +            address.setCountyDistrict("Unknown");
I wonder why you still have these Unknown! Just don't set the addresses. We have no address as unknown

2024-10-16 04:46 UTC, ojwanganto commented on api/src/main/java/org/openmrs/module/hivtestingservices/api/impl/HTSServiceImpl.java
> +@Service("htsService")
Are you sure we need to annotate the serviceImpl?

2024-10-16 04:48 UTC, ojwanganto commented on api/src/main/java/org/openmrs/module/hivtestingservices/chore/MigrateUnregisteredPatientContacts.java
> +    private static final Pattern VALID_NAME_PATTERN = Pattern.compile("[^a-zA-Z ]");
There is a global property that is used to validate names during registration. May be you can use it instead of defining a new regex

2024-10-16 04:54 UTC, ojwanganto commented on api/src/main/java/org/openmrs/module/hivtestingservices/chore/MigrateUnregisteredPatientContacts.java
> +            attributes.put(CommonMetadata._PersonAttributeType.PNS_APPROACH,
We'll end up saving null attributes. We should set the value to a non-null i.e.
`if(StringUtils.isNotBlank(pc.getPhoneContact())) {
    attributes.put(CommonMetadata._PersonAttributeType.TELEPHONE_CONTACT, pc.getPhoneContact());
}`

2024-10-16 04:55 UTC, ojwanganto requested changes
Thanks, @njorocs. Please address the comments in the PR.

2024-10-16 05:19 UTC, njorocs commented on api/src/main/java/org/openmrs/module/hivtestingservices/chore/MigrateUnregisteredPatientContacts.java
> +            address.setCountyDistrict("Unknown");
@ojwanganto I got this without setting these addresses. 
![Screenshot from 2024-10-15 19-00-47](https://github.com/user-attachments/assets/a286a6bd-7758-4049-8a7a-fcc2f4bb0ba4)

2024-10-16 06:29 UTC, ojwanganto commented on api/src/main/java/org/openmrs/module/hivtestingservices/chore/MigrateUnregisteredPatientContacts.java
> +            address.setCountyDistrict("Unknown");
I didn't realize this. It is OK

2024-10-16 06:35 UTC, njorocs commented on api/src/main/java/org/openmrs/module/hivtestingservices/chore/MigrateUnregisteredPatientContacts.java
> +        Obs obs = new Obs();
It is does not have to be associated to an encounter. Dropped setting encounter

2024-10-16 10:19 UTC, njorocs commented on api/src/main/java/org/openmrs/module/hivtestingservices/api/impl/HTSServiceImpl.java
> +@Service("htsService")
Removed the annotation.

2024-10-16 10:23 UTC, njorocs commented on api/src/main/java/org/openmrs/module/hivtestingservices/chore/MigrateUnregisteredPatientContacts.java
> +    private static final Pattern VALID_NAME_PATTERN = Pattern.compile("[^a-zA-Z ]");
Since we are doing cleanup at runtime, we need a regex that checks for anything that is not in the patient.nameValidationRegex global property using [^a-zA-Z \-] (updated to allow hyphens in the name).

2024-10-16 10:35 UTC, njorocs commented
> Thanks, @njorocs. Please address the comments in the PR.
Made the chnages. Kindly review.

2024-11-22 13:17 UTC, merged